monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - email_send
        - timing
    handlers:
        timing:
            type: fingers_crossed
            action_level: debug
            handler: nested_timing
            channels: [ timing ]
            formatter: monolog.formatter.session_request

        nested_timing:
            type: stream
            path: "%kernel.logs_dir%/timing/timing_%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.session_request

        email:
            type: rotating_file
            path: "%kernel.logs_dir%/email/email_%kernel.environment%.log"
            level: debug
            channels: [ email_send ]
            max_files: 15
            formatter: monolog.formatter.session_request

when@dev:
    monolog:
        handlers:
            security:
                type: rotating_file
                path: "%kernel.logs_dir%/security/secutity_%kernel.environment%.log"
                channels: [ security ]
                level: info
                max_files: 15
                formatter: monolog.formatter.session_request
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event"]
                max_files: 10
                formatter: monolog.formatter.session_request
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            security:
                type: rotating_file
                path: "%kernel.logs_dir%/security/secutity_%kernel.environment%.log"
                channels: [ 'security' ]
                action_level: error
                max_files: 15
                formatter: monolog.formatter.session_request
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
