name: PhpUnit Test
on: [pull_request]
jobs:
  phpunit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "latest"
          version: "latest"
          args: --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Run Unit test
        run: ./vendor/bin/phpunit --testsuite=Unitaire --colors --testdox
