name: Scans Codebase
on: [pull_request]
run-name: Cs-fixer and PhpStan analyse by ${{ github.actor }}

jobs:
  phpStan-analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Cache cs-fixer
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --dry-run

      - name: Run PhpStan
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          args: --ignore-platform-req=ext-zend-opcache